import test from 'node:test';import assert from 'node:assert/strict';
import {onRequestGet as auth} from '../functions/api/auth.js';import {onRequestGet as callback} from '../functions/api/callback.js';
const env={SITE_ORIGIN:'https://vail.example',GITHUB_CLIENT_ID:'example',GITHUB_CLIENT_SECRET:'secret',GITHUB_REPO:'owner/repo'};
test('login sets protected state cookie and exact callback',async()=>{const r=await auth({request:new Request(env.SITE_ORIGIN+'/api/auth'),env});assert.equal(r.status,302);assert.match(r.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal(new URL(r.headers.get('Location')).searchParams.get('redirect_uri'),env.SITE_ORIGIN+'/api/callback')});
test('unconfigured login stays closed',async()=>assert.equal((await auth({request:new Request(env.SITE_ORIGIN+'/api/auth'),env:{}})).status,503));
test('other origins rejected',async()=>assert.equal((await auth({request:new Request('https://other.example/api/auth'),env})).status,403));
test('missing or mismatched OAuth state rejected before token exchange',async()=>{for(const headers of [{},{Cookie:'__Host-vail_oauth=other'}])assert.equal((await callback({request:new Request(env.SITE_ORIGIN+'/api/callback?code=x&state=abc',{headers}),env})).status,400)});
test('unauthorized repository access rejected',async()=>{const old=global.fetch;try{let call=0;global.fetch=async()=>Response.json(++call===1?{access_token:'abc'}:{permissions:{push:false}});const r=await callback({request:new Request(env.SITE_ORIGIN+'/api/callback?code=x&state=abc',{headers:{Cookie:'__Host-vail_oauth=abc'}}),env});assert.equal(r.status,403)}finally{global.fetch=old}});
test('authorized callback restricts token delivery to configured origin',async()=>{const old=global.fetch;try{let call=0;global.fetch=async()=>Response.json(++call===1?{access_token:'token-for-test'}:{permissions:{push:true}});const r=await callback({request:new Request(env.SITE_ORIGIN+'/api/callback?code=x&state=abc',{headers:{Cookie:'__Host-vail_oauth=abc'}}),env});assert.equal(r.status,200);const html=await r.text();assert.match(html,/event.origin===origin/);assert.match(html,/event.source===target/);assert.ok(!html.includes("postMessage('*'"));assert.match(r.headers.get('Set-Cookie'),/Max-Age=0/)}finally{global.fetch=old}});
